stages:
  partner_in_rhyme:
    cmd: python pipeline/web_scrape_partnersinrhyme.py
  midis101_part1:
    cmd: python pipeline/midis101_part1.py
    outs:
      - pipeline/download_links.pkl
  midis101_part2:
    cmd: python pipeline/midis101_part2.py
    deps:
      - pipeline/midis101_part1.py
      - pipeline/download_links.pkl
  data_prep_train:
    cmd: python pipeline/data_prep.py --config=params.yml
    deps:
      - pipeline/web_scrape_partnersinrhyme.py
      - pipeline/midis101_part2.py
      - midi_data
    params:
      - sequence_length
      - midi_data_path
      - split_start
      - train_split
    outs:
      - processed
