sequence_length: 100
split_start: 0
train_split: 0.8
split_end: 1
train.model_loss_function: categorical_crossentropy
train.model_optimizer: rmsprop
train.epochs: 200
train.batch_size: 128
model_path: model.h5
inference.n_notes: 250 # number of notes to generate
